# Generated by Django 5.2.14 on 2026-06-08 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('aberto', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '11. Chamados de Suporte',
            },
        ),
        migrations.RenameModel(
            old_name='Backup',
            new_name='BackupSistema',
        ),
        migrations.RenameModel(
            old_name='TermoUso',
            new_name='TermoPrivacidade',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AlterModelOptions(
            name='alertaseguranca',
            options={'verbose_name_plural': '06. Alertas de Segurança'},
        ),
        migrations.AlterModelOptions(
            name='backupsistema',
            options={'verbose_name_plural': '08. Backups'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': '02. Categorias'},
        ),
        migrations.AlterModelOptions(
            name='credencial',
            options={'verbose_name_plural': '03. Credenciais'},
        ),
        migrations.AlterModelOptions(
            name='geradorconfig',
            options={'verbose_name_plural': '07. Configuração do Gerador'},
        ),
        migrations.AlterModelOptions(
            name='historicosenha',
            options={'verbose_name_plural': '05. Histórico de Senhas'},
        ),
        migrations.AlterModelOptions(
            name='logacesso',
            options={'verbose_name_plural': '04. Logs de Acessos'},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'verbose_name_plural': '10. Notificações'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name_plural': '01. Perfis de Usuários'},
        ),
        migrations.AlterModelOptions(
            name='termoprivacidade',
            options={'verbose_name_plural': '09. Termos de Uso'},
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='lembrete_senha_mestre',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='lembrete_mestre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='credencial',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
